### ISSUE TITLE
github_token argument is not optional

### ISSUE THREAD

**Issue by carlobeltrame** [imba-tjd/rebase-upstream-action#1]
When running this action as documented in the Readme, I get the following output:
```
Run imba-tjd/rebase-upstream-action@master
  with:
    branch: master
    depth: 100
+ UPSTREAM=
? How would you like to authenticate GitHub CLI?  [Use arrows to move, type to filter]
+ '[' -z ']'
> Login with a web browser
+ echo
  Paste an authentication token
+ gh auth login --with-token
25l25h
could not prompt: EOF
```

The `github_token` input to the action is not only undeclared, but also required to run the action, is that correct? Do you have any real-world examples where this action is used?

**Comment by imba-tjd** [comment]
I have noticed it. There is a bug in my code. For now you can specify `upstream`.

I'm waiting for GitHub CLI 1.7.0 to be integrated into GitHub Actions's virtual env. They often do this once a week.

**Comment by imba-tjd** [comment]
fixed

**Comment by carlobeltrame** [comment]
Cool, thanks, I'll check it out.
