### ISSUE TITLE
Check if the rebase would add any workflows and/or actions and fail

### ISSUE THREAD

**Issue by Centzilius** [imba-tjd/rebase-upstream-action#2]
I was thinking about the security of github workflows if you automatically merge any changes from a remote repository into yours. Maybe a workflow input would be helpfull to enable a functionality that checks if any files in `.github/workflows`or `.github/actions` are going to be changed and if so fail the workflow. If the user of this action actually wants to have these changes as well it would be best to do that manually or only on `workflow_dispatch` (or disable the check).

If you think this is a good idea I'll be happy to provide a PR.

**Comment by imba-tjd** [comment]
Do you mean the situation that the upstream have some workflows, and fork must enable Actions to use this repo, so it also runs potentially harmful workflows from upstream? 

If so, I prefer placing the check in normal `run` phase, and provede it as an example in Readme, rather than integrate it into this action.

**Comment by Centzilius** [comment]
Thats what I mean. I'm not sure how you could put that in the normal run phase as this would require the upstream repository to be checked out already.

**Comment by Centzilius** [comment]
I was thinking about something like
`git diff upstream/master --name-status | grep .github && exit 1`

**Comment by imba-tjd** [comment]
Oh, you are right :joy:
Ok, you are welcomed to make the PR.

**Comment by Centzilius** [comment]
Apparently this is not necessary. A similar case just happened and github just denied the push with
```
 ! [remote rejected]   master -> master (refusing to allow a GitHub App to create or update workflow `.github/workflows/ansible-lint.yml` without `workflows` permission)
 ```

**Comment by imba-tjd** [comment]
I didn't test, but I think Actions don't have that restriction by default.

Now I see GitHub has some ways to control the permission of `github.token`

* https://docs.github.com/en/actions/security-guides/automatic-token-authentication
* https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/

People can look into them if they are concerned about security.
